GET http://{{base_url}}/{{prefix}}/{{version}}/user/employee/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDAxMTU1NTUsImlhdCI6MTc0MDExNTU1NSwiaXNzIjoiSU4yRk9SRVNUIiwicm9sZSI6IkFETUlOIiwic3ViIjoxfQ.gycAgcFA9cnrO12RtEA6BZhyApVtPSFKClFduaVTkA0

PUT http://{{base_url}}/{{prefix}}/{{version}}/user/employee
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDAwNTAwOTUsImlhdCI6MTc0MDA0NjQ5NSwiaXNzIjoiSU4yRk9SRVNUIiwicm9sZSI6IkFETUlOIiwic3ViIjoxfQ.7_xZ0pjkFCloMRacOTxfSbP_gBYnngqxiB2hqA6mjvM
{
  "name": "admin2"
}
